[workspace]
resolver = "2"
members = [
    "crates/engramdb-keygen",
    "crates/engramdb-core",
    "crates/engramdb-io",
    "crates/engramdb",
    "crates/engramdb-bench",
    "crates/engramdb-python",
    "crates/engramdb-pyo3",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
