#!/usr/bin/env python3
"""Generate the frozen Engram constants for DeepSeek-V4.1-Flash.

DeepSeek-V4.1-Flash derives its Engram hash multipliers from numpy's PCG64 RNG and
its per-(layer, order, head) moduli from a running "next unused prime" search.  Both
are deterministic, but replaying them from Rust would mean reimplementing PCG64 plus
numpy's Lemire bounded-integer sampling bit-exactly, for no benefit.  Instead we
freeze the 48 primes and 8 multipliers here and let the Rust keygen treat them as
constants -- the same policy already used for the Qwen PLE path (read, never derive).

Usage:
    python3 scripts/gen_v41_engram_constants.py                 # write + verify
    python3 scripts/gen_v41_engram_constants.py --check         # verify only (CI)

Requires numpy and sympy.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np
from sympy import isprime

REPO = Path(__file__).resolve().parent.parent
CONFIG = REPO / "refs" / "v41_config.json"
OUT = REPO / "refs" / "v41_engram_constants.json"

PRIME_SEED = 10007  # official: np.random.default_rng(10007 * layer_id)


def next_prime(start: int, seen: set[int]) -> int:
    """Smallest prime above `start` not already handed out."""
    candidate = start + 1
    while not isprime(candidate) or candidate in seen:
        candidate += 1
    return candidate


def build(text_cfg: dict) -> dict:
    layer_ids = tuple(text_cfg["engram_layer_ids"])
    max_ngram_size = text_cfg["engram_max_ngram_size"]
    n_heads = text_cfg["engram_n_heads"]
    vocab_size = text_cfg["engram_vocab_size"]
    head_dim = text_cfg["engram_head_dim"]
    compressed_vocab = text_cfg["engram_compressed_vocab_size"]
    declared_rows = tuple(text_cfg["engram_num_embeddings"])

    # --- primes: one disjoint prime per (layer, n-gram order, head) -------------
    primes: list[list[list[int]]] = []
    seen: set[int] = set()
    for _ in layer_ids:
        per_layer = []
        for _ in range(max_ngram_size - 1):
            sizes = []
            current = vocab_size - 1
            for _ in range(n_heads):
                current = next_prime(current, seen)
                seen.add(current)
                sizes.append(current)
            per_layer.append(sizes)
        primes.append(per_layer)

    # --- multipliers: derived from the *compressed* vocab size -----------------
    max_long = np.iinfo(np.int64).max
    multiplier_bound = max(1, (max_long // compressed_vocab) // 2)
    multipliers = []
    for layer_id in layer_ids:
        generator = np.random.default_rng(PRIME_SEED * layer_id)
        values = generator.integers(
            low=0, high=multiplier_bound, size=(max_ngram_size,), dtype=np.int64
        )
        multipliers.append((values * 2 + 1).tolist())

    # --- closure checks --------------------------------------------------------
    row_sums = [sum(sum(order) for order in layer) for layer in primes]
    assert tuple(row_sums) == declared_rows, (row_sums, declared_rows)
    flat = [p for layer in primes for order in layer for p in order]
    assert len(flat) == len(set(flat)) == len(layer_ids) * (max_ngram_size - 1) * n_heads

    return {
        "_comment": (
            "Generated by scripts/gen_v41_engram_constants.py from refs/v41_config.json. "
            "Do not edit by hand. Source: DeepSeek-V4.1-Flash (MIT)."
        ),
        "model": "deepseek-ai/DeepSeek-V4.1-Flash",
        "layer_ids": list(layer_ids),
        "max_ngram_size": max_ngram_size,
        "n_heads": n_heads,
        "head_dim": head_dim,
        "vocab_size": vocab_size,
        "compressed_vocab_size": compressed_vocab,
        "pad_token_id": text_cfg["engram_pad_token_id"],
        "multiplier_bound": int(multiplier_bound),
        "multipliers": multipliers,
        # primes[layer_index][order_index][head]; order_index 0 => 2-gram
        "primes": primes,
        "rows_per_layer": list(declared_rows),
        "rows_total": sum(declared_rows),
        "bytes_per_row": head_dim + 8,  # FP8 payload + 8 x E8M0 scale
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="verify without writing")
    args = parser.parse_args()

    text_cfg = json.loads(CONFIG.read_text())["text_config"]
    generated = build(text_cfg)

    if args.check:
        if not OUT.exists():
            print(f"FAIL: {OUT} missing", file=sys.stderr)
            return 1
        existing = json.loads(OUT.read_text())
        if existing != generated:
            print(f"FAIL: {OUT} is stale relative to {CONFIG.name}", file=sys.stderr)
            return 1
        print(f"OK: {OUT.relative_to(REPO)} matches {CONFIG.relative_to(REPO)}")
        return 0

    OUT.write_text(json.dumps(generated, indent=2) + "\n")
    rows = generated["rows_per_layer"]
    print(f"wrote {OUT.relative_to(REPO)}")
    print(f"  rows/layer {rows}  total {generated['rows_total']:,}")
    print(f"  {len(generated['multipliers']) * generated['max_ngram_size']} multipliers, "
          f"{sum(len(o) for l in generated['primes'] for o in l)} primes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
