#!/usr/bin/env python3
"""Freeze the DeepSeek-V4.1-Flash compressed token map.

V4.1 hashes **compressed** token ids, and every hash multiplier is derived from
the compressed vocab size (99,092).  Get that number wrong and the whole table
silently rehashes -- the official code asserts it precisely because a mismatch
is invisible until outputs are wrong.

The mapping is produced by a Unicode normalization pipeline
(NFKC -> NFD -> StripAccents -> Lowercase -> whitespace collapse -> sentinel
-> Strip -> sentinel restore) applied to every token's decoded text.  Two
reasons this must be *frozen* rather than recomputed at run time:

1. Unicode normalization tables change between ICU/`tokenizers` releases.  A
   version bump could change the compressed vocab size and rehash the model.
2. Reimplementing that pipeline in Rust would be pure porting risk for zero
   benefit: it is a fixed table for a fixed tokenizer.

So we extract the table once here and ship it as a numeric artifact.  The
Rust keygen then only does integer arithmetic.

Requires the ``tokenizers`` package (and a ``tokenizer.json``), not torch.

Usage:
    python scripts/gen_v41_token_map.py --tokenizer /path/to/tokenizer.json
    python scripts/gen_v41_token_map.py --tokenizer ... --check   # verify only

Fetch the tokenizer (6.4 MB, MIT) with:
    curl -L -o /tmp/v41-tokenizer.json \\
      https://hf-mirror.com/deepseek-ai/DeepSeek-V4.1-Flash/resolve/main/tokenizer.json
"""

from __future__ import annotations

import argparse
import hashlib
import json
import struct
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT_BIN = REPO / "refs" / "v41_token_map.bin"
OUT_META = REPO / "refs" / "v41_token_map.json"
EXPECTED_COMPRESSED = 99092
EXPECTED_VOCAB = 129280


def build_compressed_token_map(backend, vocab_size: int):
    """Verbatim port of the official build_compressed_token_map (MIT).

    Only the ``len(tokenizer)`` call is parameterized, so this works with a raw
    ``tokenizers.Tokenizer`` instead of a transformers wrapper.
    """
    from tokenizers import Regex, normalizers

    sentinel = "\ue000"
    normalizer = normalizers.Sequence(
        [
            normalizers.NFKC(),
            normalizers.NFD(),
            normalizers.StripAccents(),
            normalizers.Lowercase(),
            normalizers.Replace(Regex(r"[ \t\r\n]+"), " "),
            normalizers.Replace(Regex(r"^ $"), sentinel),
            normalizers.Strip(),
            normalizers.Replace(sentinel, " "),
        ]
    )
    key_to_new: dict[str, int] = {}
    lookup = [0] * vocab_size
    for token_id in range(vocab_size):
        text = backend.decode([token_id], skip_special_tokens=False)
        if "\ufffd" in text:
            key = backend.id_to_token(token_id)
        else:
            normalized = normalizer.normalize_str(text)
            key = normalized if normalized else text
        new_id = key_to_new.get(key)
        if new_id is None:
            new_id = len(key_to_new)
            key_to_new[key] = new_id
        lookup[token_id] = new_id
    return lookup, len(key_to_new)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--tokenizer", required=True, help="path to tokenizer.json")
    ap.add_argument("--check", action="store_true", help="verify without writing")
    args = ap.parse_args()

    from tokenizers import Tokenizer

    tok_path = Path(args.tokenizer)
    if not tok_path.exists():
        print(f"FAIL: tokenizer not found: {tok_path}", file=sys.stderr)
        return 1
    raw = tok_path.read_bytes()
    digest = hashlib.sha256(raw).hexdigest()

    tok = Tokenizer.from_file(str(tok_path))
    vocab_size = len(tok.get_vocab())
    if vocab_size != EXPECTED_VOCAB:
        print(
            f"FAIL: tokenizer vocab {vocab_size} != {EXPECTED_VOCAB}", file=sys.stderr
        )
        return 1

    lookup, compressed = build_compressed_token_map(tok, vocab_size)
    if compressed != EXPECTED_COMPRESSED:
        print(
            f"FAIL: compressed vocab {compressed} != {EXPECTED_COMPRESSED}; "
            "the hash multipliers derive from this number, so the table would rehash",
            file=sys.stderr,
        )
        return 1

    payload = struct.pack(f"<{vocab_size}I", *lookup)
    meta = {
        "_comment": (
            "Generated by scripts/gen_v41_token_map.py. Do not edit by hand. "
            "Source: deepseek-ai/DeepSeek-V4.1-Flash tokenizer.json (MIT)."
        ),
        "model": "deepseek-ai/DeepSeek-V4.1-Flash",
        "tokenizer_sha256": digest,
        "tokenizer_bytes": len(raw),
        "vocab_size": vocab_size,
        "compressed_vocab_size": compressed,
        "pad_token_id": 2,
        "pad_compressed_id": lookup[2],
        "dtype": "uint32-le",
        "table_bytes": len(payload),
    }

    if args.check:
        if not OUT_BIN.exists() or not OUT_META.exists():
            print("FAIL: frozen artifacts missing", file=sys.stderr)
            return 1
        existing = json.loads(OUT_META.read_text(encoding="utf-8"))
        if existing != meta or OUT_BIN.read_bytes() != payload:
            print("FAIL: frozen artifacts are stale vs this tokenizer", file=sys.stderr)
            return 1
        print(f"OK: {OUT_BIN.name} matches ({compressed} compressed ids, {len(payload)} B)")
        return 0

    OUT_BIN.write_bytes(payload)
    OUT_META.write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {OUT_BIN.relative_to(REPO)} ({len(payload):,} bytes)")
    print(f"wrote {OUT_META.relative_to(REPO)}")
    print(
        f"  vocab {vocab_size} -> compressed {compressed}; "
        f"pad_id 2 -> {lookup[2]}; tokenizer sha256 {digest[:16]}..."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
